# Use postgres/example user/password credentials
version: '3.1'

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: myDbPass1
    ports:
      - 5432:5432

  adminer:
    image: adminer
    ports:
      - 8000:8080