DROP TABLE IF EXISTS "authority";
CREATE TABLE "authority"
(
    "id"   integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "name" character varying(255),
    CONSTRAINT "authority_pkey" PRIMARY KEY ("id")
) WITH (oids = false);


DROP TABLE IF EXISTS "to_do_list";
CREATE TABLE "to_do_list"
(
    "id"    integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "title" character varying(255),
    CONSTRAINT "to_do_list_pkey" PRIMARY KEY ("id")
) WITH (oids = false);


DROP TABLE IF EXISTS "to_do_item";
CREATE TABLE "to_do_item"
(
    "id"            integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "created"       timestamp              NOT NULL,
    "resolve"       boolean                NOT NULL,
    "text"          character varying(255) NOT NULL,
    "updated"       timestamp              NOT NULL,
    "to_do_list_id" integer,
    CONSTRAINT "to_do_item_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "fke6grn5m1lbu32q1a8eme85gmg" FOREIGN KEY (to_do_list_id) REFERENCES to_do_list (id) NOT DEFERRABLE
) WITH (oids = false);


DROP TABLE IF EXISTS "user";
CREATE TABLE "user"
(
    "id"       integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "created"  timestamp              NOT NULL,
    "password" character varying(255),
    "updated"  timestamp              NOT NULL,
    "username" character varying(255) NOT NULL,
    CONSTRAINT "uk_sb8bbouer5wak8vyiiy4pf2bx" UNIQUE ("username"),
    CONSTRAINT "user_pkey" PRIMARY KEY ("id")
) WITH (oids = false);


DROP TABLE IF EXISTS "user_authority";
CREATE TABLE "user_authority"
(
    "user_id"      integer NOT NULL,
    "authority_id" integer NOT NULL,
    CONSTRAINT "user_authority_pkey" PRIMARY KEY ("user_id", "authority_id"),
    CONSTRAINT "fkgvxjs381k6f48d5d2yi11uh89" FOREIGN KEY (authority_id) REFERENCES authority (id) NOT DEFERRABLE,
    CONSTRAINT "fkscuh0v3acg0xp6skwcvuynl6x" FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE
) WITH (oids = false);
